# Generated by Django 4.2.9 on 2024-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('img', models.ImageField(upload_to='gallery')),
                ('username', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=65)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
