# Generated by Django 4.2.9 on 2024-03-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='password',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='username',
        ),
    ]
