# Generated by Django 4.2.9 on 2024-03-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movieapp', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(default='Actor 1, Actor 2'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Default Category', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default_poster.jpg', upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_trailer_link',
            field=models.URLField(default='https://www.youtube.com/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(default='Default Description'),
        ),
    ]
