# Generated by Django 4.2.9 on 2024-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0014_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('english', 'English')], default='english', max_length=50),
        ),
    ]
